---
- name: OSPF Setup
  hosts: all
  become: yes
  vars_files:
    - defaults/main.yml
  
  tasks:
    - name: Install base tools
      apt:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
          - gpg
        state: present
        update_cache: yes

    - name: Add GPG key for FRR
      apt_key:
        url: "https://deb.frrouting.org/frr/keys.asc"
        state: present

    - name: Add FRR repository
      apt_repository:
        repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
        state: present

    - name: Install FRR packages
      apt:
        name: 
          - frr
          - frr-pythontools
        state: present

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    - name: Disable asymmetric routing blocking (rp_filter)
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present

    - name: Configure daemons
      template:
        src: templates/daemons
        dest: /etc/frr/daemons
        owner: frr
        group: frr
        mode: 0640
      notify: restart frr

    - name: Configure FRR (ospf)
      template:
        src: templates/frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      notify: restart frr

  handlers:
    - name: restart frr
      service:
        name: frr
        state: restarted
        enabled: yes
